### ISSUE TITLE
The sort order breaks in some areas in the browes tab

### ISSUE THREAD

**Issue by Phooh** [Nagru/Manga-Organizer#11]
This was a pretty small old bug that never really bothered me much til now, so I'd usually forget to report it. Basically when going down or up the list of entries, specifically artist, in alphabetical order, some names would break. Its kind of hard to explain but these pics would make more sense. 

http://i.imgur.com/NpKIGRx.jpg

 As you can see the sort order just gets interrupted by another artist's name. This wasn't much of a problem awhile ago but now its been doing it more and more in different places.

http://i.imgur.com/rqiExVk.jpg

The very first thing I tried was making sure the names are correct, retyping it, copy/pasting the title from the site, and checking the folders to see if anything is wrong but nothing. Then I tried clicking the tab orders and seeing if that fixes but I always get that same order.

**Comment by Nagru** [comment]
Found the issue. The sort action combines the artist and title text so that the results are sorted in that order. Problem is there needed to be a space inserted between the two values; otherwise we get wonky behaviour with artists whose names start with the same characters.

I'll do a little more testing and then upload the new executable.

As always, thanks for letting me know :)
