### ISSUE TITLE
Not all tags are being pulled from exhentai.

### ISSUE THREAD

**Issue by Phooh** [Nagru/Manga-Organizer#5]
I can't remember how long ago I noticed this but I know it was sometime this year. When inserting the URL to a gallery to grab the tags, not all of the tags would be taken. I would have to manually insert them into MO. It seems the tag's order would change randomly each time I try to insert a URL as well however, some tags just will not be taken.

Some examples:
http://exhentai.org/g/98363/bf68da3ce3/
http://exhentai.org/g/108368/089bbaf89b/

There's a lot more but I never bother to write them down. I'd say maybe about 20-30% of the galleries I've come across had this problem. I'm starting to think it has something to do with older tags or galleries or something.

**Comment by Nagru** [comment]
I've done a quick debug test and found that e-hentai's API isn't returning all of the tags. Offhand I assume this is due to the tag rating.

Once my apartment's fixed I'll take a closer look.

**Comment by Nagru** [comment]
Yup, pretty sure this is due to the tag rating. Try adding a new one and you'll note it's not included in the list of returned tags. If we want to get this changed it'll be a matter for Tenboro to update the API's behaviour.

I have updated how the copy&paste/drag&drop works for tags though. If you select the whole block of tags MO will auto-format them for the program.
