### ISSUE TITLE
[Not an issue]  Wishes

### ISSUE THREAD

**Issue by Zerendipity** [Nagru/Manga-Organizer#6]
Hello Nagru,

Sorry for writing it here but i did not find any other way of contacting you, please delete if this is unwanted.
Loving the project but if possible i would like to offer some changes i personally would love to see.
1) If possible have the ability to delete from the main view window.
2) Have a different menu drop down at the top of the 3 tabs with the main application settings instead of having them in the folder view.
3) Have an app config to set as a default viewer the one you did.

And this is just a wish please ignore it:
Have a preview tab that allows you to see the covers (like e-hentai) instead of a title list.

Again sorry for putting this here.

**Comment by Nagru** [comment]
No problem, Github's 'Issues' page also doubles for enhancement suggestions. My email is listed on my Git profile and in the Tutorial section of the program if you need it later.

1) Sounds good. Should be reasonable to tie a context menu to listview items. I'll give it a shot.
2) Will give it some thought. Perhaps in the top right.
3) Easy. Done. Needs some testing first but should be deployed in the next few days.

A cover browser would be cool, I completely agree. The issue is doing it properly would take <i>many</i> hours to create and test. Maybe one day.

**Comment by Zerendipity** [comment]
Amazing thank you.
